Refactor/8 redesign button
goskyai/lo-si pull request #9
Opened 2021-12-29 04:01 UTC by JerryLiao-GoSky

## 目的

Fixes #8 
覺得還是一個一個 component 推好惹

## 如何測試

1. `yarn storybook`
2. 至 http://localhost:6006/?path=/story/components-inputs-button--default 查看各種按鈕

## 預期結果

- 按鈕樣式需符合設計圖 https://www.figma.com/file/og8KJ9f4UINpdYPb3slesI/GoSky-Library-(Lo-si)?node-id=626%3A1446

## 其它修改

- 儲存時，自動觸發 vscode 的 organizeImports
- 改了一下 `global.ts` 裡的 type，讓平時開發 Styled component 時用到 `theme` 可以 auto complete

2021-12-29 09:06 UTC, JerryLiao-GoSky commented
@leo-gosky 已改完，上面 description 也有更新

2021-12-30 09:36 UTC, leo-gosky requested changes
👀

2021-12-30 09:36 UTC, leo-gosky commented on src/assets/theme/global.ts
> +  'green-300': '#AACBFF',
藍綠大和解惹

2021-12-30 09:36 UTC, leo-gosky commented on src/components/Textarea/index.tsx
>    const bgColor = disabled ? 'grey-400' : 'grey-200';
這裡的顏色應該是 100/200 了，改了顏色好像會影響滿多東西

2021-12-30 09:36 UTC, leo-gosky commented on src/components/Button/index.tsx
> +  ${variant({
在想這兩個 `variant` 如果搬出去寫成另外兩個 function 會不會比較好讀一點？

2021-12-30 09:36 UTC, leo-gosky commented on src/components/Input/Input.stories.tsx
>  Color.args = { color: 'red', value: 'Color Text' };
看不懂當初在寫什麼東西惹，不過這好像應該要讓它能改顏色才對，畢竟 storybook 上面寫的好像能改文字顏色；怪的是當初註解寫 `color` 改變的是框線顏色，當初應該是腦袋不清楚。

看看要不要讓它可以改變顏色 (應該也不會因此讓原本的 CDP 已經在使用的部分壞掉)，或是框線顏色和文字顏色分開 (可能是錯誤的時候會改動框線顏色，而不改變文字顏色？)

2022-01-04 06:33 UTC, JerryLiao-GoSky commented on src/components/Textarea/index.tsx
>    const bgColor = disabled ? 'grey-400' : 'grey-200';
大洗牌ㄎㄎ

2022-01-04 06:39 UTC, JerryLiao-GoSky commented on src/components/Button/index.tsx
> +  ${variant({
好Ｒ  我拆出去

2022-01-04 07:05 UTC, JerryLiao-GoSky commented on src/components/Input/Input.stories.tsx
>  Color.args = { color: 'red', value: 'Color Text' };
No 那時候腦袋應該是清醒 der
CDP 設計圖一開始的確所有 Input 內的文字、框線都是藍色
所以就去問了 Abby 是否其他顏色也有一樣的狀況？回答是，因此 Input 這才支援各種顏色（其他顏色這也才補上了完整的階層，因為要配合 hover、border 的階層）
後來可能有誰去反映了字吧，Input 設計圖的文字默默改回黑色，
再次跟 Abby 確認字之後都是黑色，因此[改了回來](https://github.com/goskyai/CDP-FrontEnd/commit/790ffcf9975c47727494d8ce3d13e4381cc1e30e)，並[在這個 PR](https://github.com/goskyai/CDP-FrontEnd/pull/102) 偷渡了出去

---

慶幸的是目前看起來沒有需要支援其他顏色，僅有錯誤時 border 為紅色
這和 antd 蠻一致的，所以之後整個 Input 用 antd 取代應該可以

2022-01-04 07:14 UTC, JerryLiao-GoSky commented
ok

2022-01-05 03:24 UTC, leo-gosky reviewed
看了一下綠色的值應該是 Kelvin 給錯，我就直接改掉它好惹。

提個 proposal
- `styleType` prop 就直接用 `variant` 替代，一來少一來少寫一行字，二來也比較接近大部分慣例用法
- 考慮用 `Component.defaultProps` 取代在括號中 assign 預設的值

![image](https://user-images.githubusercontent.com/78006520/148155685-e405add6-fefc-4590-b3de-8b654062a072.png)
↓
![image](https://user-images.githubusercontent.com/78006520/148155841-716c7315-c2d4-4e29-abc0-5bfbc95e33f6.png)

2022-01-05 05:53 UTC, JerryLiao-GoSky commented
@leo-gosky 歐給

2022-01-05 06:49 UTC, leo-gosky approved these changes
👍

2022-01-05 06:49 UTC, merged

2022-01-05 06:51 UTC, leo-gosky commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on:
- [GitHub release](https://github.com/goskyai/lo-si/releases/tag/v1.4.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@gosky/lo-si/v/1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: